print("Masukkan ukuran balok : ")
panjang = int(input("panjang (cm) : "))
lebar = int(input("lebar (cm) : "))
tinggi = int(input("panjang (cm) : "))
volume = panjang * lebar * tinggi
luas = 2*(panjang * lebar + panjang * tinggi + lebar * tinggi)
print(f"Ukuran Balok : ")
print(f" -  Panjang, : {panjang}  cm")
print(f" - lebar , : {lebar}  cm")
print(f" - tinggi , : {tinggi}  cm")
print(f" Hasil Perhitungan :")
print(f" - volume : {volume} cm3")
print(f" - Luas Permukaan : {luas} cm2")